### ISSUE TITLE
Request to update yarn version : An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-7.5.6.tgz: ESOCKETTIMEDOUT".

### ISSUE THREAD

**Issue by arun-madhavan-013** [alexa/alexa-smart-screen-web-components#2] opened 2023-07-19 14:24 UTC
Most of the time we are getting error from yarn install sequence for the dependencies. When checked for a solution came to know that most of the ESOCKETTIMEDOUT related issues are resolved in yarn v2.
Kindly request to update the same.
```
NOTE: Executing Tasks
ERROR: lib32-alexa-web-sdk-git-r0 do_compile: Execution of '/home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/temp/run.do_compile.3324934' failed with exit code 1
ERROR: Logfile of failure stored in: /home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/temp/log.do_compile.3324934
Log data follows:
| DEBUG: Executing shell function do_compile
| 
| > yarn@1.22.19 preinstall /home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/nodejs/node-v14.20.1-linux-x64/lib/node_modules/yarn
| > :; (node ./preinstall.js > /dev/null 2>&1 || true)
| 
| /home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/nodejs/node-v14.20.1-linux-x64/bin/yarn -> /home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/nodejs/node-v14.20.1-linux-x64/lib/node_modules/yarn/bin/yarn.js
| /home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/nodejs/node-v14.20.1-linux-x64/bin/yarnpkg -> /home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/nodejs/node-v14.20.1-linux-x64/lib/node_modules/yarn/bin/yarn.js
| + yarn@1.22.19
| updated 1 package in 3.125s
| yarn add v1.22.19
| [1/5] Validating package.json...
| [2/5] Resolving packages...
| [3/5] Fetching packages...
| info There appears to be trouble with your network connection. Retrying...
| info There appears to be trouble with your network connection. Retrying...
| info There appears to be trouble with your network connection. Retrying...
| info There appears to be trouble with your network connection. Retrying...
| error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-7.5.6.tgz: ESOCKETTIMEDOUT".
| info If you think this is a bug, please open a bug report with the information provided in "/home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/alexa-web-components/packages/alexa-smart-screen-apl/yarn-error.log".
| info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
| info There appears to be trouble with your network connection. Retrying...
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/jkuria217/accelerator/AH212/build/tmp/work/armv7at2hf-neon-rdkmllib32-linux-gnueabi/lib32-alexa-web-sdk/git-r0/temp/run.do_compile.3324934' failed with exit code 1
```

**Comment by mdaix-az** [comment] 2023-07-28 00:38
Thank your for bringing this matter to our attention. We value your input and have thoroughly examined the issue your reported. However, after conducting several tests, we found that we are unable to reproduce the issue on our side.

The "yarn ESOCKETTIMEDOUT" issue you’ve mentioned could be intermittent, often resolving itself after a few additional attempts. Alternatively, it might be associated with the network settings of your testing environment.

For the time being, we will mark this ticket as closed. However, do not hesitate to reopen it should you have any additional concerns.

**Closed as completed by mdaix-az** 2023-07-28 00:38 UTC
